import Footer from '@/components/footer'
import Header from '../components/header'
import './globals.css'

export const dynamic = 'auto'

export const metadata = {
  title: "Explorer's Guild",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white z-50'>
          <Header />
        {children}
      <Footer />
      </body>
    </html>
  )
}
